// Code generated by Slice Machine. DO NOT EDIT.

import Box from "./Box/index.svelte";
import RichText from "./RichText/index.svelte";

export const components = {
  box: Box,
  rich_text: RichText,
};
