// Code generated by Slice Machine. DO NOT EDIT.

import Boxes from "./Boxes/index.svelte";
import RichText from "./RichText/index.svelte";

export const components = {
  boxes: Boxes,
  rich_text: RichText,
};
